### ISSUE TITLE
please publish product codes and better descriptions for aws AMIs

### ISSUE THREAD

**Issue by drewmullen** [appgate/appgate#1]
i'm working on a terraform module for deploying appgate appliances.I've been able to find the catalog item product codes via `awscli`  but the naming of the images doesnt appear to be standardized. Also, when i used `most_recent = true` for the byol license it gave me 5.0.1 even though 5.3.2 exists. im sure thats because the x.x.1 patch was actually released last but the experience could be improved.

requests:
- could you please post the various app gate product codes you maintain in this readme 
- improve descriptions in the deployed images
- standardize naming. for example: what does "paid" mean? "byol" is obvious. "metered"? some clarity would help (real examples below)

```
"appgate-SDP-5.0.1-Paid-d039c81b-2ac0-4798-98c7-afcf6226c4f7-ami-0db141ea1611ebf86.4"
"AppGate-SDP-5.3.2-BYOL-2f761032-a6e6-48dc-bbe7-1a31d1d00c9c-ami-05b0d0b6208f0430a.4"
"AppGate-SDP-5.1.1-Metered-2d481428-e6e5-4a75-8e54-05f5c11b4ca9-ami-00ca32a22e3659563.4"
"AppGate Insight 1.9.0-16-a93287b4-8fa2-4bac-99d9-597a3d142adc-ami-0f1815c37afd57a2a.4"
```

**Comment by thomascellerier** [comment]
You can see that by searching for appgate in the AWS Marketplace.
Only BYOL and Paid are available.

BYOL is like you said, bring your own license and should be self-explanatory. This requires a license obtained via Appgate.

Paid and Metered are billed directly through AWS.

For Paid the pricing model is available via the AWS Marketplace page, see https://aws.amazon.com/marketplace/pp/B01IWQFEHM?ref_=aws-mp-console-subscription-detail-payg#pdp-pricing
It is used for single instance deployments with up to 25 users with a 15 days free trial, mostly for evaluation purposes.

For metered actual license usage is reported using the AWS API, you can find it here https://aws.amazon.com/marketplace/pp/prodview-2fhzg7bqt225u?ref_=unifiedsearch#pdp-pricing

AppGate Insight is an unrelated discontinued product.

**Comment by drewmullen** [comment]
thanks! honestly i think my frustration is better aimed at AWS for not providing any transparency or easy lookup function for the backend values of a product. 

thank you for clarifying the paid vs metered. 

to that point, should we have a [3rd option](https://github.com/appgate/sdp-tf-reference-architecture/pull/4/files#diff-e7e977dca06ab9bd67f71f719f65bb3867761126e14a8f1cbf63c14bb0726e8cR15) for the AMI licensing choices to include "metered" ?

**Comment by thomascellerier** [comment]
Yes that would make sense :+1:
